# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a9ab6358af0d8294b6d6495de34158a833ef151e047f64911a1c6c6d81b44d6c2a53eea9cb785fab6ee68631b4926e6cd838f0ec5c13ebfd8fa44eb3bd3a8c

test:
  secret_key_base: c04c990635769b472cf64aaae2c0d59127c4814efa0224082eb5630bad2fa8c912ce27a7a8f129b4d84aba883a0b3573e4d477a1b7f386495d27bb4cc8f33360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
